# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Physical Thoughts
email: my name and surname @ gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tracking my training and psyche
baseurl: "/training" # the subpath of your site, e.g. /blog
url: "http://gpaul.github.io" # the base hostname & protocol for your site
twitter_username: gpaul2
github_username:  gpaul

# Build settings
markdown: kramdown
